### PR TITLE
Update views.py

### PR DESCRIPTION
**Pull request by suxilog**
Add context['request'] to fix 'request' KeyError.

### CODE REVIEW

**Comment by rcoombes-gosh** [comment]
Hi, I'm currently trying to install Wagtail A/B Testing on our sites to demo it to the POs. Our sites currently run 2.15.1 and it looks like I'm running into this error. Is there any forecast on when this fix may be rolled into main?

**Comment by rcoombes-gosh** [comment]
Thanks for picking up on this and commenting in the other ticket @zerolab

**Comment by mwesterhof** [comment]
i would also like to know if there's any idea when this can be picked up. is it possible to review this PR?

**Review by KalobTaulien — APPROVED** [review]

**Comment by KalobTaulien** [comment]
@rcoombes-gosh @suxilog @mwesterhof I just released wagtail-ab-testing 0.7 with this, and #42 in.

**Pull request merged**
